// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2bb8Hq5JbR8sfKbxX9I9mjlVHI2EM83M',
    appId: '1:412919557356:web:7bbb8584b0ec0fddf0c9c9',
    messagingSenderId: '412919557356',
    projectId: 'dha-anywaa-bible-47f57',
    authDomain: 'dha-anywaa-bible-47f57.firebaseapp.com',
    storageBucket: 'dha-anywaa-bible-47f57.appspot.com',
    measurementId: 'G-F4HDKKFG93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7MGV7TjxGhTvG9HVdfZh_hKWrgV8zP9w',
    appId: '1:412919557356:android:4be68587c39c0d16f0c9c9',
    messagingSenderId: '412919557356',
    projectId: 'dha-anywaa-bible-47f57',
    storageBucket: 'dha-anywaa-bible-47f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA21s-LPWD3DYTyw68HNnIlDYwzxVXHUgk',
    appId: '1:412919557356:ios:aa5146b692e2a798f0c9c9',
    messagingSenderId: '412919557356',
    projectId: 'dha-anywaa-bible-47f57',
    storageBucket: 'dha-anywaa-bible-47f57.appspot.com',
    iosBundleId: 'com.example.dhaAnywaaBible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA21s-LPWD3DYTyw68HNnIlDYwzxVXHUgk',
    appId: '1:412919557356:ios:aa5146b692e2a798f0c9c9',
    messagingSenderId: '412919557356',
    projectId: 'dha-anywaa-bible-47f57',
    storageBucket: 'dha-anywaa-bible-47f57.appspot.com',
    iosBundleId: 'com.example.dhaAnywaaBible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2bb8Hq5JbR8sfKbxX9I9mjlVHI2EM83M',
    appId: '1:412919557356:web:8b3d4cc4ff345b5df0c9c9',
    messagingSenderId: '412919557356',
    projectId: 'dha-anywaa-bible-47f57',
    authDomain: 'dha-anywaa-bible-47f57.firebaseapp.com',
    storageBucket: 'dha-anywaa-bible-47f57.appspot.com',
    measurementId: 'G-CJVLTCH7DV',
  );
}
